version: '3.8'

services:
  # --------------------
  # 1. DATABASE (PostgreSQL for Prisma)
  # --------------------
  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chat_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # --------------------
  # 2. REDIS (for Socket.io Adapter)
  # --------------------
  redis:
    image: redis:6-alpine
    restart: always
    ports:
      - "6379:6379"

  # --------------------
  # 3. BACKEND (NestJS/PM2)
  # --------------------
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres
      - redis
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/chat_db?schema=public
      REDIS_HOST: redis
      REDIS_PORT: 6379
      NODE_ENV: production

  # --------------------
  # 4. frontend (React/Vite)
  # --------------------
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - backend
    
    ports:
      - "5000:5000"

volumes:
  postgres_data: